name: Bump formulae on schedule or request

on:
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/autobump.yml
  workflow_dispatch:
    inputs:
      formulae:
        description: Custom list of formulae to livecheck and bump if outdated
        required: false
  schedule:
    # Every 3 hours from 1 through 23 with an offset of 45 minutes
    - cron: "45 1-23/3 * * *"

permissions: {}

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  autobump:
    if: github.repository_owner == 'SMillerDev'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    container:
      image: ghcr.io/homebrew/brew:main
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          core: false
          cask: false

      - run: brew tap SMillerDev/tap

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@main

      - name: Bump formulae
        env:
          HOMEBREW_TEST_BOT_AUTOBUMP: 1
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GIT_COMMITTER_NAME: github-actions
          HOMEBREW_GIT_COMMITTER_EMAIL: 1484494+SMillerDev@users.noreply.github.com
          FORMULAE: ${{ inputs.formulae }}
        run: |
          BREW_BUMP=(brew bump --no-fork --open-pr --formulae --bump-synced)
          if [[ -n "${FORMULAE-}" ]]; then
            xargs -t "${BREW_BUMP[@]}" <<<"${FORMULAE}"
          else
            "${BREW_BUMP[@]}" --tap=SMillerDev/tap
          fi
