name: Bump formulae on schedule or request

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/autobump.yml
  schedule:
    # Every day at 01:45 UTC
    - cron: "45 1 * * *"

permissions: {}

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  autobump:
    env:
      TAP_NAME: SMillerDev/tap
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@df4b09108a1de9d6f995fe68f302b3f68bd6d2ef # 2026.07.20.1
        with:
          core: false
          cask: false

      - name: Configure Git user
        id: git
        uses: Homebrew/actions/git-user-config@9af03b7ae3f9e2ae5c174f659d5c3909f7e7dbac # 2026.07.29.1

      - name: Bump formulae
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GIT_COMMITTER_NAME: ${{ steps.git.outputs.name }}
          HOMEBREW_GIT_COMMITTER_EMAIL: ${{ steps.git.outputs.email }}
        run: |
          brew bump --no-fork --open-pr --bump-synced --tap="$TAP_NAME"
