name: Bump formulae on schedule or request

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/autobump.yml
  schedule:
    # Every day at 01:45 UTC
    - cron: "45 1 * * *"

permissions: {}

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  autobump:
    env:
      TAP_NAME: SMillerDev/tap
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@b35a29a0f83ee8b8ca07b219fc8db3d7bb88ab49 # 2026.08.10.2
        with:
          core: false
          cask: false

      - name: Configure Git user
        id: git
        uses: Homebrew/actions/git-user-config@fd832223f9f99ebf0244dd20658680e5d4aca049 # 2026.08.03.2

      - name: Bump formulae
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GIT_COMMITTER_NAME: ${{ steps.git.outputs.name }}
          HOMEBREW_GIT_COMMITTER_EMAIL: ${{ steps.git.outputs.email }}
        run: |
          brew bump --no-fork --open-pr --bump-synced --tap="$TAP_NAME"
